[project]
name = "google-alert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "orjson>=3.10.18",
    "pychromecast>=14.0.7",
]
